### ISSUE TITLE
[DUVIDA] existe um padrão para submeter os parsers?

### ISSUE THREAD

**Issue by matdsoupe** [Guilherme775/Haskell4Noobs#6]
Estou desenvolvendo os parsers para adicionar no README. Atualmente tenho quase "pronto"o de `JSON`.

Ainda quero implementar o parser de:
- `js`
- `c`
- `sass`
- `jwt`

Minha dúvida é: vocês preferem um parser cru, feito do zero, ou há a possibilidade de usar o `parsec`? Eu pessoalmente prefiro fazer todos do zero, mas ainad sim extensíveis, já que a intenção do repo é ser um roadmap. Talvez fazer os mais simples do zero e os mais complexos (`c` e `js`) com o `parsec`? 

O que vocês acham?

**Comment by Guilherme775** [comment]
A ideia era fazer os parsers do 0 from scratch mesmo, justamente pra mostrar todos os passos e como fazer em Haskell, eu mesmo ia fazer todos eles e ir adicionando ali os links no repo (também já fiz o de JSON), mas se tu quiser basta marcar o todo e adicionar o link pro repo do parser no tópico igual eu fiz com a bst ali
